--- # AWS IAM example
- hosts: localhost
  connection: local
  remote_user: ansible
  become: sudo
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Create some sample users
    iam:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      iam_type: user
      name: "{{ item }}"
      state: present
      password: "Password"
      access_key_state: create
    with_items:
    - tmp1
    - tmp2
    register: output
  - name: Show the JSON results
    debug: var=output

