--- # EC2 module volumes example
- hosts: localhost
  connection: local
  remote_user: test
  become: sudo
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Create a new volume and attach to running instance
    ec2_vol:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance: i-04e0d86b2346477c3
      # in gigs
      volume_size: 1
      device_name: sde
    register: volume_result 
