--- # EC2 module vpc example
- hosts: localhost
  connection: local
  remote_user: test
  become: sudo
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Create new VPC
    ec2_vpc_net:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      name: NewAnsibleVPC
      state: present
      cidr_block: 172.17.1.0/24
    register: vpcnetblock
  - name: Print the JSON output
    debug: msg=vpcnetblock
