--- # EC2 module vpc facts example
- hosts: localhost
  connection: local
  remote_user: test
  become: sudo
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Get information about a vpc
    ec2_vpc_net_facts:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      # would remove filter for all vpcs information
      filters:
        vpc-id: vpc-4036e026
    register: vpcnetfacts
  - name: Print out the id
    debug: var=vpcnetfacts.vpcs[0].id
