--- # EC2 module snapshot example
- hosts: localhost
  connection: local
  remote_user: test
  become: sudo
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Take a snapshot of the running instance root volume
    ec2_snapshot:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance_id: i-04e0d86b2346477c3
      device_name: /dev/xvda
      description: Root volume snapshot from Ansible test
      wait: no
    register: snapshot
