--- # EC2 module provisioning example
- hosts: localhost
  connection: local
  remote_user: test
  become: sudo
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Create basic VPC using 10.x.x.x private network range
    ec2_vpc:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      resource_tags: { "Name":"Ansible Test" }
      state: present
      cidr_block: 10.2.1.0/24
    register: vpcblock	
