--- # EC2 module remote facts
- hosts: localhost
  connection: local
  remote_user: test
  become: sudo
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Gather facts about all running EC2 instantces
    ec2_remote_facts:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
    register: remote_facts
  - debug: msg={{  remote_facts }}
