--- # EC2 module metric alarm example
- hosts: localhost
  connection: local
  remote_user: test
  become: sudo
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Create a basic cpu alarm
    ec2_metric_alarm:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      state: present
      name: AlarmTest
      metric: "CPUUtilization"
      namespace: "AWS/EC2"
      statistic: Average
      comparison: ">="
      threshold: 25.0
      period: 300
      evaluation_periods: 6
      unit: "Percent"
      description: "This alarm fies when CPU is greater than 25 percent for 30 minutes"
      dimensions: {'InstanceID':'i-04e0d86b2346477c3'}
